### ISSUE TITLE
WYSIWYG override not working

### ISSUE THREAD

**Issue by hp7** [otago/silverstripe-retina-images#1]
Code not working in 3.2.1

$fields->removeFieldFromTab('Root.Main', 'Content');
$fields->addFieldToTab('Root.Main', 
    HtmlEditorField::create('Content', _t('SiteTree.HTMLEDITORTITLE', 'Content', 'HTML editor title')),
    'Metadata'
);

**Comment by torleif** [comment]
@hp7 I tried this in 3.2.1 and it seems to work. What error did you get? note the code snippet requires 'Metadata' to not be removed beforehand, and that you've done a ?flush=1 in the admin section first

**Comment by hp7** [comment]
Thank you
I'll take another try with a clean install

**Comment by torleif** [comment]
@hp7 I've updated the readme to use the replacefield() function instead of deleting the old one and recreating it. It's was a bit sloppy on my behalf to to do that as it assumed you have the metadata field.
