### ISSUE TITLE
Updating an image in RetinaImageHtmlEditorField doesn't work

### ISSUE THREAD

**Issue by anselmdk** [otago/silverstripe-retina-images#5]
When using the normal editor, clicking the "insert media" button allows you to update your image:

![screenshot 2016-01-19 09 18 55](https://cloud.githubusercontent.com/assets/1316533/12413376/b07fd430-be8e-11e5-8eb1-55c311661d33.png)

Once clicked, this will appear:

![screenshot 2016-01-19 09 24 32](https://cloud.githubusercontent.com/assets/1316533/12413388/c02fa90a-be8e-11e5-947a-32a8afeff24c.png)

This seems to be broken when using `RetinaImageHtmlEditorField`. Instead, this appears:

![screenshot 2016-01-19 09 19 48](https://cloud.githubusercontent.com/assets/1316533/12413397/d29de868-be8e-11e5-825c-63c99e30da95.png)

**Comment by torleif** [comment]
Thanks for that @anselmdk, it's been fixed with 4bde0a8

**Comment by anselmdk** [comment]
sweet!
